import './ScrollableBox.scss';
export default function ScrollableBox(){
    return(
        <>
         <div className="scrollable-box">
      <div className="content">
        <div className="conta_table_one">
        <table>
            <tr><p>Smeg</p></tr>
            <tr>Гродторгмаш</tr>
            <tr>Mach Easy</tr>
            <tr>Krupps</tr>
        </table>
        <table>
            <tr>Abat</tr>
            <tr>Dihr</tr>
            <tr>Adler</tr>
            <tr>MEC</tr>
        </table>
        <table>
            <tr>Comenda</tr>
            <tr>Elettrobar</tr>
            <tr>Solis</tr>
            <tr>Meiko</tr>
        </table>
        <table>
            <tr>Kocateq</tr>
            <tr>Silanos</tr>
            <tr>Amika</tr>
            <tr>Omniwash</tr>
        </table>
        <table>
            <tr>Apach</tr>
            <tr>Electrolux</tr>
            <tr>Fagor</tr>
            <tr>Tatra</tr>
        </table>
        <table>
            <tr>Modular</tr>
            <tr>Vortmax</tr>
            <tr>ATA</tr>
            <tr>Viatto</tr>
        </table>
        <table>
            <tr>Compack</tr>
            <tr>EKSI</tr>
            <tr>Kromo</tr>
            <tr>Winterhalter</tr>
        </table>
        <table>
            <tr>Apach</tr>
            <tr>Electrolux</tr>
            <tr>Fagor</tr>
            <tr>Tatra</tr>
        </table>
        </div>

        <div className="conta_table_one">
        <table>
            <tr>Smeg</tr>
            <tr>Гродторгмаш</tr>
            <tr>Mach Easy</tr>
            <tr>Krupps</tr>
        </table>
        <table>
            <tr>Abat</tr>
            <tr>Dihr</tr>
            <tr>Adler</tr>
            <tr>MEC</tr>
        </table>
        <table>
            <tr>Comenda</tr>
            <tr>Elettrobar</tr>
            <tr>Solis</tr>
            <tr>Meiko</tr>
        </table>
        <table>
            <tr>Kocateq</tr>
            <tr>Silanos</tr>
            <tr>Amika</tr>
            <tr>Omniwash</tr>
        </table>
        <table>
            <tr>Apach</tr>
            <tr>Electrolux</tr>
            <tr>Fagor</tr>
            <tr>Tatra</tr>
        </table>
        <table>
            <tr>Modular</tr>
            <tr>Vortmax</tr>
            <tr>ATA</tr>
            <tr>Viatto</tr>
        </table>
        <table>
            <tr>Compack</tr>
            <tr>EKSI</tr>
            <tr>Kromo</tr>
            <tr>Winterhalter</tr>
        </table>
        <table>
            <tr>Apach</tr>
            <tr>Electrolux</tr>
            <tr>Fagor</tr>
            <tr>Tatra</tr>
        </table>
        </div>

      </div>
    </div>
        </>
    )
}